### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by Hela-Girl** [djsudduth/mindmap-markdown#2]
Good afternoon, Don!
Perhaps you will have some free time this month to see how you can set up converting a file to *.canvas?

**Comment by djsudduth** [comment]
I've looked at it a couple of times. Much more complex than the mindmap. Requires positions and colors which will be a different parsing technique. It will be while before I can get to it - I have a couple of other open source projects to update first.  Thanks for pushing though!

**Comment by Hela-Girl** [comment]
Thanks for answering. I'll wait, I have no choice anyway. Can I write to you in a month, maybe you’ll have a minute?

**Comment by djsudduth** [comment]
@Hela-Girl just wanted to let you know I had done some updates to fix some of the input/output`-i` and `-o` switches. Some of the code was lost in the process. I believe I recovered everything - but, be sure to make a backup of `mindmd.py` before you download the latest changes. I haven't looked at canvas additions yet. I will soon.

**Comment by Hela-Girl** [comment]
Thank you for making changes to the code. I look forward to the finalization.

**Comment by Hela-Girl** [comment]
```
** Mindmap Markdown v-0.0.2 **

Mindmap: mindmaps/Rain-game.smmx ----> Markdown: markdown/Rain-game.md
Traceback (most recent call last):
  File "C:\Users\MaX\Downloads\111\mindmap-markdown-main\mindmd.py", line 414, in <module>
    main()
  File "C:\Users\MaX\Downloads\111\mindmap-markdown-main\mindmd.py", line 368, in main
    write_output(DEFAULT_MINDMAP, outfile, nums, vs)
  File "C:\Users\MaX\Downloads\111\mindmap-markdown-main\mindmd.py", line 270, in write_output
    sm_nodes = parse_mind_map(infile)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MaX\Downloads\111\mindmap-markdown-main\mindmd.py", line 168, in parse_mind_map
    topic_node.title = topic.get('text').replace('\\N',' ')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```
So far, this is the error with these startup parameters:
python mindmd.py -i mindmaps/Rain-game.smmx -o markdown/Rain-game.md

**Comment by djsudduth** [comment]
Sorry - when I readded the code I missed a line. Just put a `#` in front of line 168 so it looks like this:
`      # topic_node.title = topic.get('text').replace('\\N',' ')
        topic_node.title = topic.get('text')
`

**Comment by djsudduth** [comment]
@Hela-Girl - fixed

**Comment by Hela-Girl** [comment]
https://i.imgur.com/vqC3VaX.jpeg

**Hurray it seems to be working**. Thank you for your quick response. It's a pity that it's not canvas.

**Comment by djsudduth** [comment]
Hi @Hela-Girl  - I'm starting to look at export to Canvas now. Can you provide to a link to one of your mindmaps - preferably somewhat simple but reflects what you want? I can't start with a huge mindmap - but, maybe one with 5-10 branches and some attached images in the way you like?  
Thx!!

**Comment by Hela-Girl** [comment]
https://mega.nz/folder/I7pBSBgb#7b_h0svNZvcbbrByAoqIag

Thank you for not forgetting about me! The link contains 2 files, one very small and the second a little larger (with external files), for testing. Please note that the images are connected to the knot by invisible threads, in addition to the knots that are also connected to each other.

**Comment by djsudduth** [comment]
Thx @Hela-Girl - got them. One question for you. Your examples are more visual and probably don't need a markdown note for each node. In my case I do since my mindmaps have notes within each node and I want an Obsidian note for each. I'm wondering if you only need a canvas for visualization and no notes??

**Comment by Hela-Girl** [comment]
hi @djsudduth, I think the notes will be useful since I made the map specifically the simplest one for the test.

**Comment by Hela-Girl** [comment]
hi @djsudduth, do you have some time this month to try to implement the canvas?

**Comment by djsudduth** [comment]
Hey @Hela-Girl ! I made some progress but had to stop and fix another application. Good timing, however, I'm back at it! I'll let you know soon.

**Comment by Hela-Girl** [comment]
Thanks for your answer and have a nice day!

**Comment by Hela-Girl** [comment]
hi @djsudduth, maybe there will be a few days off in August to finish with the “canvas”?

**Comment by djsudduth** [comment]
@Hela-Girl - made some progress but having some issues to work through. I think I need to refactor the app (since it was a quick-hit need in the first place). But, let me see if I can at least get you a prototype to look at.

**Comment by Hela-Girl** [comment]
Good afternoon, can you spend some time on this thread this month?

**Comment by djsudduth** [comment]
@Hela-Girl sorry on the delay - I promise I'll get to it

**Comment by djsudduth** [comment]
@Hela-Girl  I've created a new 'develop' branch to start the work. It isn't functional yet, but new Canvas code will be there until the release is done.

**Comment by Hela-Girl** [comment]
This is great news!

**Comment by djsudduth** [comment]
@Hela-Girl  getting there...
![image](https://github.com/user-attachments/assets/e0a53193-ba05-4ddd-b7c6-f8e242525d27)

**Comment by Hela-Girl** [comment]
Hello, great news! Does it support images?

**Comment by djsudduth** [comment]
Getting there soon...

**Comment by Hela-Girl** [comment]
Thank you very much for not giving up on what you started.

**Comment by djsudduth** [comment]
Closer - there are still some weird issues with what Obsidian supports vs SimpleMind

![image](https://github.com/user-attachments/assets/546be39f-e003-400f-9448-b7827a64e624)

**Comment by Hela-Girl** [comment]
Wow, the beginning is already visible! This is the most important thing!

**Comment by djsudduth** [comment]
Ok, @Hela-Girl  - first BETA version is ready for some testing. Please be gentle to start with some basic examples. Here's what you need to do:
1. Backup or make a copy your current version of mindmd.py 
2. Go to the branch here in Github called 'develop'
3. Download the entire `develop` zip file into a new testing directory
4. The new switch to create the Obsidian canvas file is -c (so `python mindmd.py -c`)
5. If the -c is used, then every simplemind node becomes a new markdown note and the canvas file is given the 'output name'.canvas
6. Run the default test of the sample file with `python mindmd.py -c` which will give you an example
7. The files have relative paths in the new test directory. I would suggest running this BETA version outside of Obsidian directories and then just copy all the files from the default `markdown` and `markdown/media' directories to Obsidian manually 

Let me know what you discover!

**Comment by Hela-Girl** [comment]
https://i.imgur.com/RlnCnju.jpeg
and
https://i.imgur.com/zxco0yo.jpeg

It works, but not all paths are there and there are a lot of extra files that probably also need to be processed somehow. Or maybe I configured something wrong...

https://mega.nz/file/4zJ2HQSD#bBl8bbF7DQ9X7RS2fZ_1kiuqXFlgxKMTkYmjzkgqrRI
Link to file as an example.

**Comment by djsudduth** [comment]
Fix has been added. Download the latest in `develop`.

![image](https://github.com/user-attachments/assets/8fd1ed58-9f9d-4ca0-aaff-26882fe57475)

**Comment by djsudduth** [comment]
PS - I'm adding a new scale factor in the settings that will allow you to stretch or contract the Canvas. Should be ready later today.

**Comment by Hela-Girl** [comment]
https://i.imgur.com/9Dw63Hc.jpeg

BETA!!! Mindmap Markdown v-0.0.7 - Is it the latest version?

**Comment by Hela-Girl** [comment]
P.S.: In the Obsidian program, my canvas files are located in the list folder and the images are in the Rain-game\(Picture files) folder. Tell me how to correctly configure the configuration file so that the relative path begins with the images\ folder?

images\
    Rain-game\(Picture files)
list\
    Rain-game.canvas

**Comment by djsudduth** [comment]
We're not there yet (to determine the final paths in your Obsidian vault). 

Create the `betamarkdown` folder in your mindmd 0.0.7 install folder before running the beta version (that's why you have the error). Then run your tests with the beta folders. After running a mindmap file, copy the entire `betamarkdown` folder and subfolder manually to your Obsidian vault to verify things. Once your testing is done and I fix those bugs just delete that folder in your Obsidian vault.

**Comment by Hela-Girl** [comment]
https://i.imgur.com/nK8GQDG.jpeg
and
https://i.imgur.com/zftAEwC.jpeg

At the moment I noticed that the text fields that should be on the canvas have turned into files, can this be fixed?

**Comment by Hela-Girl** [comment]
[SETTINGS]
input_path = mindmaps/
output_path = betamarkdown/
media_path = media/
test_file_name = Rain-game.smmx
canvas_path = blank

https://i.imgur.com/yh7YeY4.jpeg
p.s.: For some reason it doesn’t create images in this build.

**Comment by djsudduth** [comment]
@Hela-Girl Can you run try running Rain-games.smmx 2 times in a row and see if the error appears the second time?  I have the same error - but it seems to be due to the large unzip of all the images. They are there but the program runs before they are all completely written to disk. When I run it the the second time through, I don't get the image missing error.

**Comment by Hela-Girl** [comment]
In the previous build it worked for me the second time, the images were shown now no. I checked additionally, neither from 1 nor from 5 images are extracted.

**Comment by djsudduth** [comment]
Updated to v0.0.8 - this should fix the "image file.... missing or not accessible" error. I ran `Rain-games.smmx` in various directories and there were no errors and all images were in the Canvas. I also added a scale factor `canvas_scale` in `settings.cfg` that let's you condense or expand the canvas. Right now it is set to 2.0. If you want images closer/tighter then set it to 1.5.

**Comment by djsudduth** [comment]
I need to add that your canvas is pushing Obsidian to the edge. Sometimes you'll have to restart Obsidian to get the graph to draw. 230 images is a lot and Obsidian may not be able to handle more.

**Comment by Hela-Girl** [comment]
> I need to add that your canvas is pushing Obsidian to the edge. Sometimes you'll have to restart Obsidian to get the graph to draw. 230 images is a lot and Obsidian may not be able to handle more.

There are significantly larger sheets with images, the problem with a large number of images is solved using a plugin that writes images to a new folder each time, example in the screenshots:
https://i.imgur.com/vTR0RkN.jpeg
https://i.imgur.com/REx5eD3.jpeg
https://i.imgur.com/q7T31WJ.jpeg

**Comment by Hela-Girl** [comment]
> Updated to v0.0.8 - this should fix the "image file.... missing or not accessible" error. I ran `Rain-games.smmx` in various directories and there were no errors and all images were in the Canvas. I also added a scale factor `canvas_scale` in `settings.cfg` that let's you condense or expand the canvas. Right now it is set to 2.0. If you want images closer/tighter then set it to 1.5. You still need to set `output_path` to some directory within the 0.0.8 folder and then copy that entire folder to Obsidian manually. Here are some of the things I'm working on in next updates:
> 
> 1. Add relation links
> 2. Option to create Obsidian canvas text nodes vs markdown file nodes from the Simplemind tree nodes
> 3. Path fixes to allow export directly to the Obsidian vault

Your script works great, but I don’t understand how to transfer images to obsidian, the screenshot shows that there are no images, what should be the path? Tell me please.
https://i.imgur.com/4hayObx.jpeg

In addition to images, the script contained text and links, but your script creates files, can this be fixed?
https://i.imgur.com/lMX1nhu.jpeg

**Comment by djsudduth** [comment]
Hi! 
For your second question about files vs text - that is #2 in the list of things to fix - not done yet:
2. Option to create Obsidian canvas text nodes vs markdown file nodes from the Simplemind tree nodes

Your images right now in 0.0.8 have to be a subfolder off the Canvas folder. So, if the Canvas file is created in `betamarkdown`, all the files have to be in `betamarkdown/images` or `betamarkdown/media` (whatever you used in the `settings.cfg`. 

If the settings look like:
[SETTINGS]
input_path = mindmaps/
output_path = betamarkdown/
media_path = media/
test_file_name = Rain-game.smmx

Then the images need to be in `betamarkdown/media` in Obsidian. If you copy the parent `betamarkdown` folder the images should be copied as well. My point #3 will be to fix that and be more flexible:
3. Path fixes to allow export directly to the Obsidian vault

Just to note - if there are any plugins involved that will have to be outside this utility as a separate script.

Let me know what you discover!

**Comment by djsudduth** [comment]
Ok, version 0.0.9 beta is ready. It fixes these two things:
- Add relation links
- Path fixes to allow export directly to the Obsidian vault

So, now you can export directly to your Obsidian vault! A few things to remember in `settings.cfg`:
1. The `output_path` needs to point to your Obsidian parent vault directory like `c:/Notes/Obsidian`
2. the `media_path` is relative to the parent vault. So, if you want the Canvas in `c:/Notes/Obsidian/list` and the images in `c:/Notes/Obsidian/images` then the `media_path` needs to be `../images/`.  The `../` moves up one directory so that `list` and `images` are at the same level.
3. Since the utility doesn't know where your Obsidian vault is, you need to set the `obsidian_vault_name` to the parent vault name (in my case it is just called `Obsidian`). Example: if your parent vault is `c:/Movies/Notes/MyVault` then the vault name needs to be `MyVault`. I hope that makes sense.

I've tried to configure this version's `settings.cfg` close to what you mentioned - `list` and `images`

You may have to restart Obsidian to get the images to draw after conversion. 

I haven't done the work on text nodes vs markdown file nodes yet.

**Comment by Hela-Girl** [comment]
Good evening, it’s probably evening here. I opened the files and images. There was confusion because I did not understand where the “root” was in obsidian. I discovered a few things that can be fixed:

1. Set automatic image size.
2. Connection with images in obsidian there are no such “lines” only for images. I don't know what to do here. Maybe you know what can be used?

https://i.imgur.com/YLD778K.jpeg
https://i.imgur.com/VDWDwIk.jpeg

**Comment by Hela-Girl** [comment]
P.S.: If you don’t mind, please add the line to the code: If there is no folder specified in the configuration, the script will create it.

**Comment by djsudduth** [comment]
Unfortunately Simplemind doesn't include lines for external images in their smmx files - so adding lines will have to be on the backburner for a while. I'm going to create these as separate issues since the thread is getting very long:

1. Option to create Obsidian canvas text nodes vs markdown file nodes from the Simplemind tree nodes
2. Create subdirectories automatically if they don't exist
3. Determine how to add lines for external connected images that don't exist in smmx files
4. Remove unwanted markdown in Canvas node titles

I'm going to release what I have ow as a full release 0.1.0 that supports Canvases now - so, that will be step 1. 

Let me know what is most important for you in this list 1 to 4. I'm assuming 1 is the most important.

**Comment by Hela-Girl** [comment]
For me it is important:
1. text blocks (which are now created as separate files)
2. Most likely the same arrow as the default one in obsidian or is there another type of “connection” lines in obsidian?
4. Sorry, I didn’t understand what needs to be done.

https://i.imgur.com/zMTegXL.jpeg

P.S.: I did not understand some points due to inaccuracies in the translation.

**Comment by redheaddy** [comment]
Hi!
When do you plan to finish the plugin?

**Comment by djsudduth** [comment]
@redheaddy and @Hela-Girl  - in progress on update: 
1 - Option to create Obsidian canvas text nodes vs markdown file nodes from the Simplemind tree nodes

**Comment by djsudduth** [comment]
@redheaddy  and @Hela-Girl  - I'm going to close this issue out. If you have comments on the features or would like a new feature, please update the current issues or add individual requests in the issues list. Thanks!!!

**Comment by Hela-Girl** [comment]
@djsudduth I'm only interested in the links that Simplemind uses to link to the photo on the canvas. I have no idea how to release them in Obsidian. Do you have any ideas?

**Comment by djsudduth** [comment]
@Hela-Girl - we can continue the conversation on that in this link -> #9
